### PR TITLE
updated software member

### PR DESCRIPTION
**Pull request by hari-sikchi**

### CODE REVIEW

**Comment by shubh-agrawal** [comment]
If you are trying to get your name onto website I would recommend to add your fellow mates as well. Ask all 2nd years for their profile picture and then send a pull request.

**Comment by hari-sikchi** [comment]
I told you to check if the formats ok so that i can put others profile on webpage

**Comment by hari-sikchi** [comment]
@shubh-agrawal mera add karo baki apne aap bhejege

**Comment by abinashmeher999** [comment]
I agree. Others who want their name on the website can anyway copy what he
did and he wouldn't have to wait.

**Comment by hari-sikchi** [comment]
link
https://drive.google.com/file/d/0Bwllk8LlcEAyMzIxN2lOUkNrWXM/view?usp=sharing

@abinashmeher999

**Pull request merged**
